SPREADSHEET_URL = "https://docs.google.com/spreadsheets/d/1Dt74KFYNrdjTlQsMwjM0XsvepBnWHG3iBHQjOaE_t5E/edit?usp=sharing"

# ==========================================
# 1. Google スプレッドシート API 認証情報
# ==========================================
[connections.gsheets]
type = "service_account"
project_id = "peppy-ratio-482314-p2"
private_key_id = "35ea10719d5615de87b7c7ceaa246a5f55132658"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC7pR4zg1ML/BD6\nplzMWIbKGGKi12hv/+K3XSo2SndUqAkzj7F/Ew0QyJ4+tOqp5S9elylNvn9/oY8h\n5gdElc3T3uo3diChTMozMS/EN0ZC+Yh2lTB8HyQcDAZWs2WyB2Ec6/FipLGUVEiX\nFYkn/Ml+K9QT7J9yJ1VJnaYUqyMz9Hks9HPFsBTHSjYl63hCaYzvm7gCgfgEsuIV\nz06G7Pf8Ckk/11dDz7Icvf+ce4DBHD0Ux6EcvB8ZlFku1Oxqsj2orQMWMRs19mn2\n2JR6Y6YnjTAxfUEf1Hj7zXSYE1ZGWkW6Xts9zgEriT0oqfYuAZ4jZ+K4XaM11C+4\nMc088mJxAgMBAAECggEAATdK8SZEO08rF+2VmR16GtlX/5OLLATGXO4VEv/1AGbj\nJoU6PNKzOn49eCQGB8bI/P7zz99uWrFBxpsxai+G1bP96ONZYq0QRQXoGAhwvLX6\npmQ32/wOCN4jJwVufIKgRH/WbEY0oFJuAH7I9s5/uGolwnymuV1itYzmQIjJTmr2\nsGXnDAfcD5bfkMGtO601//HomDUghnbcpmzJt+g3VnLhAcS019N9xy3u8gv4aGBG\nkNDMNBSmQP4wmAtbcZigXr8kM2rJ/MGlZKMgYR223BZhM8gogF7aZP6ZEVtjayUz\nd5omga05PQmXvKG9+2eRoorkgr7UlUOjGLXJjWbAyQKBgQDidAQXaMQjZVZI1Tyn\nBgI2EU68kpfsnlEHLDGjkLUzgZe5RbOEy8CrKUcGnbCGy8JLPb7sNcnmZftuYXmM\nsFWfMhCIoKRgXqZRBH7HIyRURKbt2/AwWy0kHgzUN40s8dR2b49hqZzRuIVsWXIF\no/1AAr7pzrCQ/O3fpAnSzjR5uQKBgQDUINThk0hDpnkXh1Ncp0qiEYnqMth/tB+L\naLYc0DekN1Jk4Bo30xp+GjTAqySPbEIds7lwnQWLs/cHOoiDt/OPrLyFqVdl5YQr\na04Ba+abXMlYOkXn/NUcyqPhn41Y4D4Yxzmg4rS1Om76YnNHBoaWkkSkLnp3JGmI\n0lx/v9CqeQKBgGopgZGH6AvAAkd60EhtJLQ8QPFeuCKRxeLa8RqBSLGw23RcHODw\ntI6Jd2a+nndTJu8nL06FmPWOceU5hUZTlJBhZCbpSKZ1OPtaZCTvcKSg2rFAHsZM\nuEjqXZFPybt8U+KCQnHClmYrX0GAXVgPnTZZEy+BWn1eVhY2TPSq/ybhAoGAFRCd\nkzj4+B7T7440rQK/2pA7TdJ2xVexujpPu1TB8cC8od/POrPv8Y3Qp0FXhBaQCjsK\nszAkmNbqNQGPBOWDfkT9A5jpYOkF0vn46RM59zujkutWfc8RqqZE1+bsNmMuR2+h\nPWTF5SlEVADqyabQPquPvW4QIzyubjPVk6oMoqECgYB4ZC9ssDXSpDP0yOeEv68L\nAkmCX5o5phNsXS1VuI/1apq7zBdK2fI+vIq6Pzywj4fuYewfeRfl5ksvGhslwYSw\nlNewBaLXjOLjMQWtT3RLDNR+fbNDbP9u/ETKU3ObKQxPgr+MBVwkbKmI9209GL1d\n8cMz1f222qSevCwVbZdSdg==\n-----END PRIVATE KEY-----\n"
client_email = "baseball-manager@peppy-ratio-482314-p2.iam.gserviceaccount.com"
client_id = "108100373929813632142"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/baseball-manager%40peppy-ratio-482314-p2.iam.gserviceaccount.com"

# ==========================================
# 2. 選手除外リスト
# ==========================================
HIDDEN_PLAYERS_TOTAL = ["助っ人1", "助っ人2", "依田裕樹", "清水さん", "居也勇貴", "知見寺明司", "鮫田叶夢", "前島和貴", "濱瑠晟", "にまさん", "小林高知", "堤はるか", "藤本隆之輔"]
FIXED_EXCLUDE_LIST = ["助っ人1", "助っ人2", "依田裕樹", "小峠海晴"]

# ==========================================
# 3. 選手と背番号のデータ
# ==========================================
[PLAYER_NUMBERS]
"佐藤蓮太" = "1" 
"久保田剛志" = "2"
"坂本昂士" = "3"
"水谷真智" = "4"
"河野潤樹" = "5"
"渡邉誠也" = "7" 
"岡﨑英一" = "8"
"中尾建太" = "10"
"内藤洋輔" = "11"
"大高翼" = "13"
"小野拓朗" = "15"
"古屋翔" = "17"
"伊東太建" = "18"
"渡邉竣太" = "19"
"山田大貴" = "21"
"志村裕三" = "23"
"石田貴大" = "24"
"相原一博" = "25"
"田中伸延" = "26"
"渡辺羽" = "28"
"石原圭佑" = "29"
"名執栄一" = "30"
"荒木豊" = "31"
"永井雄太" = "33"
"小野慎也" = "38"
"清水智広" = "43"
"名執雅叶" = "51"
"山縣諒介" = "60"
"照屋航" = "63"
"望月駿" = "66"
"鈴木翔大" = "73"

# 新規・背番号なし
"名執雅楽" = ""
"名執冬雅" = ""
"開田凌空" = ""
"杉山颯" = ""
"塚田晴琉" = ""
"野澤貫太" = ""
"横田一起" = ""
"石岡佳樹" = ""
"山中啓至" = ""
"矢崎拓也" = ""
"中村卓歳" = ""
"古屋駿" = ""
"前田琳太郎" = ""
"上島赳明" = ""
"助っ人1" = ""
"助っ人2" = ""
"助っ人3" = ""
"助っ人4" = ""
"助っ人5" = ""